server:
  servlet:
    context-path: /vaanigaInvest/
spring:
  datasource:
    password: vaaniga_invadmin
    url: jdbc:mysql://houseoftexspares.com:3306/vaaniga_invest
    username: vaaniga_invadmin
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 714892763843-g6qre0ab62klviqgpeokfmedr9nmjecj.apps.googleusercontent.com
            clientSecret: FGb4O0X-8O_U6A_d4qTeqFF3